# Generated by Django 5.2.17 on 2026-09-19 07:30

# migration แรกของโปรเจกต์: สร้างตารางผู้ใช้ (accounts.User) พร้อม constraint ของอีเมล/รหัส/บทบาท
# ต้องมีก่อนตารางอื่นทุกตารางที่อ้างถึงผู้ใช้ (ดู AUTH_USER_MODEL ใน config/settings.py)

import accounts.managers
import accounts.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='อีเมล')),
                ('student_or_staff_id', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[accounts.validators.validate_staff_id], verbose_name='รหัสนักศึกษา/พนักงาน')),
                ('role', models.CharField(choices=[('admin', 'ผู้ดูแลระบบ'), ('teacher', 'ผู้สอน'), ('student', 'ผู้เรียน')], default='student', max_length=10, verbose_name='บทบาท')),
                ('first_name', models.CharField(max_length=150, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=150, verbose_name='นามสกุล')),
                ('first_name_en', models.CharField(blank=True, max_length=150, verbose_name='ชื่อ (อังกฤษ)')),
                ('last_name_en', models.CharField(blank=True, max_length=150, verbose_name='นามสกุล (อังกฤษ)')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='ยืนยันอีเมลแล้ว')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('is_staff', models.BooleanField(default=False, verbose_name='เข้า Django admin ได้')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='รูปโปรไฟล์')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่เริ่มใช้งาน')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ผู้ใช้',
                'verbose_name_plural': 'ผู้ใช้',
                'constraints': [models.CheckConstraint(condition=models.Q(('email', django.db.models.functions.text.Lower('email'))), name='accounts_user_email_lowercase'), models.CheckConstraint(condition=models.Q(('student_or_staff_id__isnull', True), models.Q(models.Q(('student_or_staff_id', ''), _negated=True), models.Q(('student_or_staff_id__contains', '@'), _negated=True)), _connector='OR'), name='accounts_user_staff_id_valid'), models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'teacher', 'student'])), name='accounts_user_role_valid')],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
