# Generated by Django 5.2.17 on 2026-09-19 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='แฮชของโทเคน')),
                ('purpose', models.CharField(choices=[('verify_email', 'ยืนยันอีเมล'), ('reset_password', 'ตั้งรหัสผ่าน')], max_length=20, verbose_name='จุดประสงค์')),
                ('expires_at', models.DateTimeField(verbose_name='หมดอายุเมื่อ')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='ใช้เมื่อ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ออกเมื่อ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'โทเคนในลิงก์อีเมล',
                'verbose_name_plural': 'โทเคนในลิงก์อีเมล',
                'constraints': [models.CheckConstraint(condition=models.Q(('purpose__in', ['verify_email', 'reset_password'])), name='accounts_emailtoken_purpose_valid')],
            },
        ),
    ]
