# Generated by Django 5.2.17 on 2026-09-20 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'สร้าง'), ('update', 'แก้ไข'), ('delete', 'ลบ'), ('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ'), ('impersonate_start', 'เริ่มสวมสิทธิ์'), ('impersonate_end', 'สิ้นสุดการสวมสิทธิ์'), ('publish', 'เผยแพร่'), ('enroll', 'ลงทะเบียนเข้ารายวิชา'), ('unenroll', 'ถอนออกจากรายวิชา'), ('regrade', 'คำนวณคะแนนใหม่')], max_length=20, verbose_name='การกระทำ')),
                ('object_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='รหัสวัตถุ')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='ข้อความแทนวัตถุ')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='ค่าที่เปลี่ยน')),
                ('context', models.JSONField(blank=True, null=True, verbose_name='บริบท')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เวลา')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_actor', to=settings.AUTH_USER_MODEL, verbose_name='ผู้กระทำ')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='ชนิดของวัตถุ')),
                ('impersonated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_impersonated', to=settings.AUTH_USER_MODEL, verbose_name='สวมสิทธิ์โดย')),
            ],
            options={
                'verbose_name': 'ประวัติการกระทำ',
                'verbose_name_plural': 'ประวัติการกระทำ',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_auditlog_target_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['create', 'update', 'delete', 'login', 'logout', 'impersonate_start', 'impersonate_end', 'publish', 'enroll', 'unenroll', 'regrade'])), name='audit_auditlog_action_valid')],
            },
        ),
    ]
